# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EvangVitalData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EvangVitalData
  pod 'SnapKit', '~> 5.0.0'

  target 'EvangVitalDataTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EvangVitalDataUITests' do
    # Pods for testing
  end

end
